# Generated by Django 2.0.7 on 2018-07-15 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('game_complexity', models.FloatField()),
                ('game_time', models.IntegerField()),
                ('game_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('match_date', models.DateField(verbose_name='Match Date')),
                ('match_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameMatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_standing', models.IntegerField()),
                ('result_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.GameMatch')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('player_photo', models.ImageField(height_field=24, upload_to='', width_field=24)),
            ],
        ),
        migrations.AddField(
            model_name='gamematchresult',
            name='result_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Player'),
        ),
        migrations.AddField(
            model_name='gamematch',
            name='match_players',
            field=models.ManyToManyField(to='rankings.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='gamematchresult',
            unique_together={('result_player', 'result_match')},
        ),
    ]
