# Generated by Django 2.0.7 on 2018-07-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20180715_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='match_players',
        ),
        migrations.AddField(
            model_name='gamematch',
            name='match_player',
            field=models.ForeignKey(default='dbicho', on_delete=django.db.models.deletion.CASCADE, to='rankings.Player'),
            preserve_default=False,
        ),
    ]
