# Generated by Django 2.0.7 on 2018-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20180715_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamematchresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gamematchresult',
            name='result_match',
        ),
        migrations.RemoveField(
            model_name='gamematchresult',
            name='result_player',
        ),
        migrations.AddField(
            model_name='gamematch',
            name='match_player_standing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='gamematch',
            unique_together={('match_player', 'id')},
        ),
        migrations.DeleteModel(
            name='GameMatchResult',
        ),
    ]
