# Generated by Django 2.0.7 on 2018-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_auto_20180715_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='match_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gamematch',
            unique_together={('match_player', 'match_id')},
        ),
    ]
