# Generated by Django 2.0.7 on 2018-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20180715_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
