# Generated by Django 2.0.7 on 2018-07-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20180715_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_standing', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamematch',
            name='match_players',
            field=models.ManyToManyField(to='rankings.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='gamematch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamematchresult',
            name='result_match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.GameMatch'),
        ),
        migrations.AddField(
            model_name='gamematchresult',
            name='result_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Player'),
        ),
        migrations.RemoveField(
            model_name='gamematch',
            name='match_player',
        ),
        migrations.RemoveField(
            model_name='gamematch',
            name='match_player_standing',
        ),
        migrations.RemoveField(
            model_name='gamematch',
            name='match_points',
        ),
        migrations.AlterUniqueTogether(
            name='gamematchresult',
            unique_together={('result_match_id', 'result_player', 'result_standing')},
        ),
    ]
