# Generated by Django 2.0.7 on 2018-07-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_auto_20180716_1446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamematchresult',
            unique_together={('result_match_id', 'result_player')},
        ),
    ]
