# Generated by Django 2.0.7 on 2018-07-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0010_auto_20180716_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_standing', models.IntegerField()),
                ('table_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamematchresult',
            name='result_points',
            field=models.FloatField(null=True),
        ),
    ]
