# Generated by Django 2.0.7 on 2018-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20180716_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematchresult',
            name='result_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
