# Generated by Django 2.0.7 on 2018-07-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0012_auto_20180716_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalClassification',
            fields=[
                ('standing_position', models.IntegerField(primary_key=True, serialize=False)),
                ('score_points', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='totalclassification',
            unique_together={('standing_position', 'player')},
        ),
    ]
